package org.morphql.jetbrains

/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by packages/language-definitions/export-json.ts
 */
object MorphQLConstants {
    val KEYWORDS = setOf(
        "from",
        "to",
        "transform",
        "unsafe",
        "set",
        "section",
        "where",
        "multiple",
        "clone",
        "delete",
        "define",
        "if",
        "else",
        "modify",
        "return"
    )

    val FUNCTIONS = setOf(
        "substring",
        "split",
        "replace",
        "text",
        "number",
        "uppercase",
        "lowercase",
        "extractnumber",
        "xmlnode",
        "to_base64",
        "from_base64",
        "aslist",
        "spreadsheet",
        "unpack",
        "pack",
        "list",
        "array",
        "floor",
        "ceil",
        "round",
        "abs",
        "fixed",
        "min",
        "max",
        "trim",
        "padstart",
        "padend",
        "indexof",
        "startswith",
        "endswith"
    )

    val OPERATORS = setOf(
        "===",
        "!==",
        "==",
        "!=",
        "<=",
        ">=",
        "<",
        ">",
        "&&",
        "||",
        "!",
        "+",
        "-",
        "*",
        "/",
        "%",
        "="
    )
}
