package org.morphql.jetbrains

/**
 * GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by packages/language-definitions/export-json.ts
 */
object MorphQLDocumentation {
    val DOCS = mapOf(
        "from" to """
            <b>from <format></b><br/>
            Specifies the input data format.<br/><br/>
            <b>Parameters:</b><ul><li><b>format:</b> If used as first keyword: The starting format name (e.g., `json`, `xml`, `csv`, `plaintext`, `object`). When used after a section, defines its source.</li></ul>
            <b>Example:</b><pre>from json to csv</pre>
        """.trimIndent(),
        "to" to """
            <b>to <format></b><br/>
            Specifies the output data format.<br/><br/>
            <b>Parameters:</b><ul><li><b>format:</b> The name of one of the available adapters.</li></ul>
            <b>Example:</b><pre>from csv to json</pre>
        """.trimIndent(),
        "transform" to """
            <b>transform [unsafe]</b><br/>
            Begins the transformation block containing actions. Optional 'unsafe' keyword disables safety features (optional chaining) for maximum performance.<br/><br/>
            
            <b>Example:</b><pre>transform
  set name = firstName

transform unsafe
  set result = price / quantity</pre>
        """.trimIndent(),
        "unsafe" to """
            <b>transform unsafe</b><br/>
            Disables safety features (optional chaining) in generated code for maximum performance. Use only with validated/trusted input data.<br/><br/>
            
            <b>Example:</b><pre>transform unsafe
  set result = price / quantity</pre>
        """.trimIndent(),
        "set" to """
            <b>set <target> = <expression></b><br/>
            Assigns a value to a field in the output.<br/><br/>
            <b>Parameters:</b><ul><li><b>target:</b> The field name to set</li><li><b>expression:</b> The value or expression to assign</li></ul>
            <b>Example:</b><pre>set fullName = firstName + " " + lastName</pre>
        """.trimIndent(),
        "section" to """
            <b>section [multiple] <name>( [subquery] <actions> ) [from <path>] [where <condition>]</b><br/>
            Creates a nested object or array in the output. Can optionally include a subquery for format conversion and a where clause for filtering.<br/><br/>
            <b>Parameters:</b><ul><li><b>multiple:</b> (Optional) Treat as array mapping</li><li><b>name:</b> The section/field name</li><li><b>subquery:</b> (Optional) Nested query: from <format> to <format> [transform]</li><li><b>actions:</b> Actions to perform within the section</li><li><b>from:</b> (Optional) Source path for the section data</li><li><b>where:</b> (Optional) Condition to filter source items (only for arrays)</li></ul>
            <b>Example:</b><pre>section multiple items(
  set name = A
) from rows where age > 18</pre>
        """.trimIndent(),
        "where" to """
            <b>section ... where <condition></b><br/>
            Filters elements in a section based on a condition. Only works when the source is an array.<br/><br/>
            <b>Parameters:</b><ul><li><b>condition:</b> Boolean expression to evaluate for each item</li></ul>
            <b>Example:</b><pre>section multiple users(set name = A) from rows where status == 'active'</pre>
        """.trimIndent(),
        "multiple" to """
            <b>section multiple <name>(...)</b><br/>
            Modifier for `section` to map over an array.<br/><br/>
            
            <b>Example:</b><pre>section multiple items(
  set id = itemId
) from products</pre>
        """.trimIndent(),
        "clone" to """
            <b>clone([field1, field2, ...])</b><br/>
            Copies fields from the source to the output.<br/><br/>
            <b>Parameters:</b><ul><li><b>fields:</b> (Optional) Specific fields to clone. If omitted, clones all fields.</li></ul>
            <b>Example:</b><pre>clone(id, name, email)</pre>
        """.trimIndent(),
        "delete" to """
            <b>delete <field></b><br/>
            Removes a field from the output (useful after `clone`).<br/><br/>
            <b>Parameters:</b><ul><li><b>field:</b> The field name to delete</li></ul>
            <b>Example:</b><pre>clone()
delete password</pre>
        """.trimIndent(),
        "define" to """
            <b>define <alias> = <expression></b><br/>
            Creates a local variable/alias for use in subsequent expressions.<br/><br/>
            <b>Parameters:</b><ul><li><b>alias:</b> The variable name</li><li><b>expression:</b> The value to assign</li></ul>
            <b>Example:</b><pre>define taxRate = 0.22
set totalWithTax = total * (1 + taxRate)</pre>
        """.trimIndent(),
        "if" to """
            <b>if (condition) ( actions ) [else ( actions )]</b><br/>
            Conditional execution of action blocks.<br/><br/>
            <b>Parameters:</b><ul><li><b>condition:</b> Boolean expression</li><li><b>actions:</b> Actions to execute if true/false</li></ul>
            <b>Example:</b><pre>if (age >= 18) (
  set status = "adult"
) else (
  set status = "minor"
)</pre>
        """.trimIndent(),
        "else" to """
            <b>else ( actions )</b><br/>
            Defines the else branch of an `if` statement.<br/><br/>
            
            <b>Example:</b><pre>if (condition) (
  ...
) else (
  ...
)</pre>
        """.trimIndent(),
        "modify" to """
            <b>modify <target> = <expression></b><br/>
            Modifies a field in the output by reading from the target (not source). Useful for post-processing already-mapped values.<br/><br/>
            <b>Parameters:</b><ul><li><b>target:</b> The field name to modify</li><li><b>expression:</b> The expression to assign (reads from target, not source)</li></ul>
            <b>Example:</b><pre>set total = price * quantity
modify total = total * 1.10</pre>
        """.trimIndent(),
        "return" to """
            <b>return <expression></b><br/>
            Returns a value from the transformation, bypassing the default serialization. Reads from target context by default.<br/><br/>
            <b>Parameters:</b><ul><li><b>expression:</b> The value to return</li></ul>
            <b>Example:</b><pre>set computed = price * 1.1
return computed</pre>
        """.trimIndent(),
        "substring" to """
            <b>substring(str, start, [length])</b><br/>
            Extracts a portion of a string. Supports negative indices.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The source string</li><li><b>start:</b> Starting index (0-based, negative counts from end)</li><li><b>length:</b> (Optional) Number of characters to extract</li></ul>
            <b>Example:</b><pre>substring("Hello World", 0, 5)  // "Hello"
substring("Hello World", -5)     // "World"</pre>
        """.trimIndent(),
        "split" to """
            <b>split(str, [separator], [limit])</b><br/>
            Splits a string into an array.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to split</li><li><b>separator:</b> (Optional) Delimiter string. Default: ""</li><li><b>limit:</b> (Optional) Maximum number of splits</li></ul>
            <b>Example:</b><pre>split("a,b,c", ",")  // ["a", "b", "c"]</pre>
        """.trimIndent(),
        "replace" to """
            <b>replace(str, search, replacement)</b><br/>
            Replaces occurrences in a string.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The source string</li><li><b>search:</b> The substring to find</li><li><b>replacement:</b> The replacement string</li></ul>
            <b>Example:</b><pre>replace("Hello World", "World", "MorphQL")  // "Hello MorphQL"</pre>
        """.trimIndent(),
        "text" to """
            <b>text(value)</b><br/>
            Converts a value to a string.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The value to convert</li></ul>
            <b>Example:</b><pre>text(123)  // "123"</pre>
        """.trimIndent(),
        "number" to """
            <b>number(value)</b><br/>
            Converts a value to a number.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The value to convert</li></ul>
            <b>Example:</b><pre>number("42")  // 42</pre>
        """.trimIndent(),
        "uppercase" to """
            <b>uppercase(str)</b><br/>
            Converts a string to uppercase.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to convert</li></ul>
            <b>Example:</b><pre>uppercase("hello")  // "HELLO"</pre>
        """.trimIndent(),
        "lowercase" to """
            <b>lowercase(str)</b><br/>
            Converts a string to lowercase.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to convert</li></ul>
            <b>Example:</b><pre>lowercase("HELLO")  // "hello"</pre>
        """.trimIndent(),
        "extractnumber" to """
            <b>extractnumber(str)</b><br/>
            Extracts the first numeric sequence from a string.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to extract from</li></ul>
            <b>Example:</b><pre>extractnumber("Price: 100USD")  // 100</pre>
        """.trimIndent(),
        "xmlnode" to """
            <b>xmlnode(value, [attrKey, attrVal, ...])</b><br/>
            Wraps a value for XML output with optional attributes.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The node content</li><li><b>attrKey, attrVal:</b> (Optional) Pairs of attribute keys and values</li></ul>
            <b>Example:</b><pre>xmlnode(content, "id", 1, "type", "text")</pre>
        """.trimIndent(),
        "to_base64" to """
            <b>to_base64(value)</b><br/>
            Encodes a string value to Base64.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The string to encode</li></ul>
            <b>Example:</b><pre>to_base64("hello")  // "aGVsbG8="</pre>
        """.trimIndent(),
        "from_base64" to """
            <b>from_base64(value)</b><br/>
            Decodes a Base64 string value.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The Base64 string to decode</li></ul>
            <b>Example:</b><pre>from_base64("aGVsbG8=")  // "hello"</pre>
        """.trimIndent(),
        "aslist" to """
            <b>aslist(value)</b><br/>
            Ensures a value is an array. Useful for input formats like XML that might return a single object or an array for the same field.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The value to normalize</li></ul>
            <b>Example:</b><pre>aslist(items)  // Always returns an array</pre>
        """.trimIndent(),
        "spreadsheet" to """
            <b>spreadsheet(data)</b><br/>
            Converts spreadsheet-style data (array of arrays) into an array of objects with named properties. First row is treated as headers.<br/><br/>
            <b>Parameters:</b><ul><li><b>data:</b> Array of arrays (rows)</li></ul>
            <b>Example:</b><pre>spreadsheet(csvData)  // Converts [["name","age"],["John",30]] to [{name:"John",age:30}]</pre>
        """.trimIndent(),
        "unpack" to """
            <b>unpack(str, fieldSpec1, [fieldSpec2, ...])</b><br/>
            Extracts multiple fields from a fixed-length string into an object. Specs follow the pattern "name:start:length[:modifier]".<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The fixed-length string to unpack</li><li><b>fieldSpec:</b> Field definition: "name:start:length". Optional ":raw" modifier at the end disables auto-trimming.</li></ul>
            <b>Example:</b><pre>unpack(source, "id:0:5", "name:5:20", "padding:25:5:raw")</pre>
        """.trimIndent(),
        "pack" to """
            <b>pack(obj, fieldSpec1, [fieldSpec2, ...])</b><br/>
            Encodes an object into a fixed-length string using field specifications. Specs follow the pattern "name:start:length[:modifier]".<br/><br/>
            <b>Parameters:</b><ul><li><b>obj:</b> The object containing data to pack</li><li><b>fieldSpec:</b> Field definition: "name:start:length". Optional ":left" modifier at the end uses left-padding (right-alignment).</li></ul>
            <b>Example:</b><pre>pack(target, "id:0:5:left", "name:5:20")</pre>
        """.trimIndent(),
        "list" to """
            <b>list(value1, [value2, ...])</b><br/>
            Creates an array from the given arguments. Useful for constructing nested structures in a single assignment.<br/><br/>
            <b>Parameters:</b><ul><li><b>values:</b> Values to include in the array</li></ul>
            <b>Example:</b><pre>list("A", "B", list("C1", "C2"))  // ["A", "B", ["C1", "C2"]]</pre>
        """.trimIndent(),
        "array" to """
            <b>array(value1, [value2, ...])</b><br/>
            Alias for `list()`. Creates an array from the given arguments.<br/><br/>
            <b>Parameters:</b><ul><li><b>values:</b> Values to include in the array</li></ul>
            <b>Example:</b><pre>array(1, 2, 3)  // [1, 2, 3]</pre>
        """.trimIndent(),
        "sum" to """
            <b>sum(array, valueExpression)</b><br/>
            Sums a numeric expression evaluated per item across an array. null, undefined and non-numeric values are treated as 0.<br/><br/>
            <b>Parameters:</b><ul><li><b>array:</b> The array to sum over</li><li><b>valueExpression:</b> Expression evaluated for each item to extract the numeric value. Bare field names resolve against each item.</li></ul>
            <b>Example:</b><pre>set total = sum(orders, amount)
set discounted = sum(items, price * quantity)</pre>
        """.trimIndent(),
        "groupby" to """
            <b>groupby(array, keyExpression)</b><br/>
            Groups an array of items by a key expression evaluated per item. Returns an array of `{ key, items }` objects in insertion order. Typically used as the `from` source of a `section multiple`.<br/><br/>
            <b>Parameters:</b><ul><li><b>array:</b> The array to group</li><li><b>keyExpression:</b> Expression evaluated for each item to compute the group key. Bare field names resolve against each item.</li></ul>
            <b>Example:</b><pre>section multiple byCategory(
  set category = key
  set count = length(items)
  section multiple products(
    set name = name
  ) from items
) from groupby(products, category)</pre>
        """.trimIndent(),
        "floor" to """
            <b>floor(value)</b><br/>
            Rounds a number down to the nearest integer.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The number to round down</li></ul>
            <b>Example:</b><pre>floor(4.9)  // 4</pre>
        """.trimIndent(),
        "ceil" to """
            <b>ceil(value)</b><br/>
            Rounds a number up to the nearest integer.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The number to round up</li></ul>
            <b>Example:</b><pre>ceil(4.1)  // 5</pre>
        """.trimIndent(),
        "round" to """
            <b>round(value, [mode])</b><br/>
            Rounds a number to the nearest integer. Mode controls tie-breaking: "half-up" (default) rounds .5 away from zero; "half-even" uses banker's rounding (rounds .5 to the nearest even integer).<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The number to round</li><li><b>mode:</b> (Optional) Rounding mode: "half-up" (default) or "half-even"</li></ul>
            <b>Example:</b><pre>round(4.5)              // 5  (half-up)
round(4.5, "half-even") // 4  (banker's)
round(3.5, "half-even") // 4  (banker's)</pre>
        """.trimIndent(),
        "abs" to """
            <b>abs(value)</b><br/>
            Returns the absolute value of a number.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The number</li></ul>
            <b>Example:</b><pre>abs(-42)  // 42</pre>
        """.trimIndent(),
        "fixed" to """
            <b>fixed(value, [decimals], [mode])</b><br/>
            Formats a number to a fixed number of decimal places. Mode controls tie-breaking: "half-up" (default) rounds .5 away from zero; "half-even" uses banker's rounding. Returns a string. Default decimals: 2.<br/><br/>
            <b>Parameters:</b><ul><li><b>value:</b> The number to format</li><li><b>decimals:</b> (Optional) Number of decimal places. Default: 2</li><li><b>mode:</b> (Optional) Rounding mode: "half-up" (default) or "half-even"</li></ul>
            <b>Example:</b><pre>fixed(2.5, 2)              // "2.50"  (half-up)
fixed(2.5, 2, "half-even") // "2.50"  (banker's, no tie at 2 decimals)
fixed(2.5, 0, "half-even") // "2"     (banker's, rounds to even)</pre>
        """.trimIndent(),
        "min" to """
            <b>min(a, b, ...)</b><br/>
            Returns the smallest of two or more numbers.<br/><br/>
            <b>Parameters:</b><ul><li><b>a, b, ...:</b> Numbers to compare</li></ul>
            <b>Example:</b><pre>min(3, 1, 4)  // 1</pre>
        """.trimIndent(),
        "max" to """
            <b>max(a, b, ...)</b><br/>
            Returns the largest of two or more numbers.<br/><br/>
            <b>Parameters:</b><ul><li><b>a, b, ...:</b> Numbers to compare</li></ul>
            <b>Example:</b><pre>max(3, 1, 4)  // 4</pre>
        """.trimIndent(),
        "trim" to """
            <b>trim(str)</b><br/>
            Removes leading and trailing whitespace from a string.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to trim</li></ul>
            <b>Example:</b><pre>trim("  hello  ")  // "hello"</pre>
        """.trimIndent(),
        "padstart" to """
            <b>padstart(str, length, [char])</b><br/>
            Pads the start of a string with a character until it reaches the target length.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to pad</li><li><b>length:</b> Target total length</li><li><b>char:</b> (Optional) Pad character. Default: " "</li></ul>
            <b>Example:</b><pre>padstart(id, 8, "0")  // "00000042"</pre>
        """.trimIndent(),
        "padend" to """
            <b>padend(str, length, [char])</b><br/>
            Pads the end of a string with a character until it reaches the target length.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to pad</li><li><b>length:</b> Target total length</li><li><b>char:</b> (Optional) Pad character. Default: " "</li></ul>
            <b>Example:</b><pre>padend(name, 20)  // "Alice               "</pre>
        """.trimIndent(),
        "indexof" to """
            <b>indexof(str, search)</b><br/>
            Returns the index of the first occurrence of a substring. Returns -1 if not found.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to search in</li><li><b>search:</b> The substring to find</li></ul>
            <b>Example:</b><pre>indexof("hello world", "world")  // 6</pre>
        """.trimIndent(),
        "startswith" to """
            <b>startswith(str, prefix)</b><br/>
            Returns true if the string starts with the given prefix.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to check</li><li><b>prefix:</b> The prefix to look for</li></ul>
            <b>Example:</b><pre>startswith("hello", "he")  // true</pre>
        """.trimIndent(),
        "endswith" to """
            <b>endswith(str, suffix)</b><br/>
            Returns true if the string ends with the given suffix.<br/><br/>
            <b>Parameters:</b><ul><li><b>str:</b> The string to check</li><li><b>suffix:</b> The suffix to look for</li></ul>
            <b>Example:</b><pre>endswith("hello", "lo")  // true</pre>
        """.trimIndent()
    )
}
